### ISSUE TITLE
Great, there are tons of ways to program in Malbolge

### ISSUE THREAD

**Issue by Btup** [MilkyWay90/Malbolge-Amplified#1]
I don't know if you have already made all of the Malbolge programming tips not work anymore (only 3); there are still [many](https://esolangs.org/wiki/Malbolge_programming) ways that you (probably) haven't covered yet.

**Comment by MilkyWay90** [comment]
The only way to program in Malbolge listed on that page that I don't cover is immutable NOPs, and programming in Malbolge uses all three of the weaknesses, and two of those are patched in this version.

**Comment by MilkyWay90** [comment]
Why did you change the title?

**Comment by MilkyWay90** [comment]
Just came back to this after another year, pardon my past self for wrongly dismissing this. I've pretty much given on anything relating to Malbolge for now, but you're free to make your own Malbolge Amplified!
